# Generated by Django 5.2.8 on 2026-01-07 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroupJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('journal_url', models.URLField()),
                ('group_amount', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
